"""QR Code path column in truck table

Revision ID: 06478d289d2b
Revises: 1fcbf9ad4645
Create Date: 2024-04-25 07:53:46.174625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06478d289d2b'
down_revision = '1fcbf9ad4645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_codePath', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_column('qr_codePath')

    # ### end Alembic commands ###
