"""Operation-GarbegAlert

Revision ID: 170d5b6b3f33
Revises: 9761fdbdc89c
Create Date: 2024-04-17 18:49:27.249213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170d5b6b3f33'
down_revision = '9761fdbdc89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garbageAlerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('picture', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truckId', sa.Integer(), nullable=False),
    sa.Column('alertId', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alertId'], ['garbageAlerts.id'], ),
    sa.ForeignKeyConstraint(['truckId'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('garbageAlerts')
    # ### end Alembic commands ###
