"""QR Code column in truck table

Revision ID: 1fcbf9ad4645
Revises: b4207967f31d
Create Date: 2024-04-25 06:17:48.729039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcbf9ad4645'
down_revision = 'b4207967f31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
