"""empty message

Revision ID: 8b25b2d73923
Revises: 44010b3833e3
Create Date: 2024-05-12 14:42:08.749340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b25b2d73923'
down_revision = '44010b3833e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_column('isActive')

    # ### end Alembic commands ###
