"""Initial migration

Revision ID: 9761fdbdc89c
Revises: 
Create Date: 2024-04-16 19:48:15.305615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9761fdbdc89c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truckTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeName', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeName', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wilayas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('matricule', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dayras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('wilayaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wilayaId'], ['wilayas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('dayraId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dayraId'], ['dayras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=25), nullable=False),
    sa.Column('lastName', sa.String(length=25), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phoneNumber', sa.String(length=15), nullable=False),
    sa.Column('municipalityId', sa.Integer(), nullable=False),
    sa.Column('houseNumber', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('birthPlace', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('userTypeId', sa.Integer(), nullable=False),
    sa.Column('imageFile', sa.String(length=50), nullable=False),
    sa.Column('joinDate', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['municipalityId'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['userTypeId'], ['userTypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('truckTypeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['truckTypeId'], ['truckTypes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('trucksReports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truckId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['truckId'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trucksReports')
    op.drop_table('trucks')
    op.drop_table('users')
    op.drop_table('municipalities')
    op.drop_table('dayras')
    op.drop_table('wilayas')
    op.drop_table('userTypes')
    op.drop_table('truckTypes')
    # ### end Alembic commands ###
