"""addition status garbageAlert column

Revision ID: b4207967f31d
Revises: 170d5b6b3f33
Create Date: 2024-04-22 20:31:49.937077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4207967f31d'
down_revision = '170d5b6b3f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garbageAlerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('trucksReports', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucksReports', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('garbageAlerts', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
