"""QR Code path column in truck table

Revision ID: c16713fb848a
Revises: 06478d289d2b
Create Date: 2024-04-25 11:48:53.081425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16713fb848a'
down_revision = '06478d289d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.alter_column('matricule',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.alter_column('matricule',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
