"""empty message

Revision ID: c9efe52a7f0d
Revises: c16713fb848a
Create Date: 2024-04-25 11:54:08.150284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9efe52a7f0d'
down_revision = 'c16713fb848a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.alter_column('qr_codePath',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.alter_column('qr_codePath',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
