"""empty message

Revision ID: cd71ec52d94f
Revises: 
Create Date: 2024-04-27 00:57:38.711585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd71ec52d94f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
